language: node_js

node_js:
  - "10"
  - "12"
  - "13"
  - "14"

script:
  - npm test
  - npm audit

after_script:
  - >
    if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
      npm run coveralls
    fi

os:
  - "linux"
  - "osx"
  - "windows"
  
