language: node_js
sudo: false

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

install:
  - node_version=$(node -v); if [ ${node_version:1:2} -ge 10 ]; then npm i -g npm@6; npm ci; else npm install; fi


script:
  - npm test
  - node_version=$(node -v); if [ ${node_version:1:2} -ge 10 ]; then npm audit; fi

after_script:
  - npm run coveralls
  
